site_name: ИСП РАН + ОГУ
site_url: https://oreluniver.ispras.ru/

theme:
  name: material
  language: ru
  logo: ISP_logo_RU.png
  font: false
  palette:
    scheme: default
    primary: white
  features:
    - navigation.top
    - navigation.instant
    - navigation.expand
    - navigation.tabs.sticky
    - toc.follow
    - search.highlight
    - search.suggest
    - content.code.copy

plugins:
  - search:
      lang: ru
  - macros
  - glightbox

nav:
  - Главная: index.md
  - Охват групп: coverage.md
  - Публикации: publications.md

extra:
  generator: false

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - md_in_html
  - toc:
      permalink: "¶"